### ISSUE TITLE
Demo didn't show any plots by default (difficult for first-time User)

### ISSUE THREAD

**Issue by drjdpowell** [justiceb/BluePlot#1]
When I installed the package and tried running the Demo, I was confused by seeing no plots.  Took me a long time to figure out that I needed to set the Plot Names in the giant config cluster to certain names like "Sine Wave" or "White Noise".  There is no documentation on this; I had to dig deep into the BluePlotDemo code.

**Comment by justiceb** [comment]
I honestly wasn't planning to hammer out a user or developer guide, because I sometimes question whether or not the community would really look at this code.

But since you asked, I spent some time this morning writing a decent README:
- https://github.com/justiceb/BluePlot/blob/main/README.md
- User guide
- Developer guide

I also uploaded a new package to VIPM:
- context help for API VIs
- DEMO loads a config on launch

**Comment by drjdpowell** [comment]
> because I sometimes question whether or not the community would really look at this code.

The README looks very good, but note that a typical User story (which I tend to follow) is:

- What is this package?  Let's install it.
- Where's the examples?  Are they easy to find.
- If so, run the example; does it show me something interesting?
- If interesting, look at the block diagram of the example.  Is it easily understandable?
- If understandable, maybe I'll read the documentation.  Maybe.

So if you want community interest, the example is very important, and you can't rely on the User actually reading anything at all unless they impressed by your example.

**Comment by justiceb** [comment]
Insightful, thanks!

Hopefully the example is a bit easier to engage with now that it loads a plot config on startup.
